version: 2

updates:
  - package-ecosystem: gomod
    directory: "/.github"
    schedule:
      interval: daily
    open-pull-requests-limit: 1
    rebase-strategy: "disabled"
    groups:
      actions:
        patterns:
          - "*"