name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: test (timestamp-authority)
        run: |
          export SIGSTORE_TIMESTAMP_VERSION=$(grep "github.com/sigstore/timestamp-authority" go.mod | awk '{print $2}')
          wget https://github.com/sigstore/timestamp-authority/releases/download/${SIGSTORE_TIMESTAMP_VERSION}/timestamp-server-linux-amd64 -O /tmp/timestamp-server
          chmod +x /tmp/timestamp-server
          # Run the TSA in background
          /tmp/timestamp-server serve --port 3000 --disable-ntp-monitoring &
          export TEST_SIGSTORE_TIMESTAMP_AUTHORITY_URL="http://localhost:3000/api/v1/timestamp"
          echo $SIGSTORE_TIMESTAMP_VERSION
